name: Spellcheck

on: [push]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Perform Spellcheck
        uses: UnicornGlobal/spellcheck-github-actions@master
